# Build config for the reference counter program.
BASEDIR:=$(CURDIR)/build
# Location of the installed Thru C SDK (default install path).
THRU_C_SDK_DIR:=$(HOME)/.thru/sdk/c/thru-sdk
include $(THRU_C_SDK_DIR)/thru_c_program.mk
